spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:hexagonal
    driverClassName: org.h2.Driver
    username: sa
    passowrd: 1234

  h2:
    console:
      enabled: true
      path: /h2-console