spring:
  datasource:
    url: jdbc:h2:mem:hexagonal
    driverClassName: org.h2.Driver
    username: sa
    passowrd:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false